name: AWS EC2-Deploy with Smart

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 다운로드 (simple-web)
        uses: actions/checkout@v2

      - name: AWS CLI 접속정보 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: 아티팩트 만들기 (deploy.zip)
        run: |
          zip -r deploy.zip .

      - name: S3 아티팩트 업로드
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.S3_BUCKET_NAME }}/deploy.zip

      - name: 진행중인 배포 중단
        run: |
          deployments=$(aws deploy list-deployments --application-name simple-web-content --deployment-group-name simple-web-content-group --query "deployments" --output text)
          for id in $deployments; do
            aws deploy stop-deployment --deployment-id $id
          done

      - name: 새로운 배포 시작
        run: |
          aws deploy create-deployment \
            --application-name simple-web-content \
            --deployment-group-name simple-web-content-group \
            --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=deploy.zip \
            --file-exists-behavior OVERWRITE

      - name: 배포 완료까지 대기
        run: |
          echo "Waiting for deployment to complete..."

